#!/bin/bash

# Installs all necessary packages necessary for development and testing
# NOTE: assumes ubuntu / debian. To install docker and protoc, you may need to use a different package manager for your OS.

# node / yarn

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install node -y
nvm use node
npm install -g yarn -y

# protobuf compiler
PB_REL="https://github.com/protocolbuffers/protobuf/releases"
curl -LO $PB_REL/download/v32.1/protoc-32.1-linux-x86_64.zip
unzip protoc-32.1-linux-x86_64.zip -d $HOME/.local
export PATH="$PATH:$HOME/.local/bin"

# install project dependencies & generate protobufs (postinstall script)
yarn

# docker

curl -O https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb
sudo apt update
sudo apt install ./docker-desktop-amd64.deb -y
